FROM python:3.10.12-bookworm AS builder

COPY requirements-frozen.txt requirements-frozen.txt
RUN pip3 install -r requirements-frozen.txt

COPY app /app

COPY log_conf.yaml firebase-admin-key.json /

ENV ENVIRONMENT 'PROD'

ENTRYPOINT [ "python3", "/app/main.py" ]